version: '3.7'
services:
   client:
      build:
         context: ./frontend
         dockerfile: Dockerfile
      env_file: .env
      ports:
         - "3000:3000"
      networks:
         - frontend
      volumes:
         - ./frontend:/app
         - /app/node_modules
   api:
      build:
         context: ./backend
         dockerfile: Dockerfile
      env_file: .env
      ports:
         - "5000:5000"
      networks:
         - frontend
         - backend
      volumes:
         - ./backend:/app
networks:
   frontend:
      driver: bridge
   backend:
      driver: bridge
